version: '2'
services:
  nginx:
    image: nginx:stable
    ports:
     - "${APP_PORT}:80"
    networks:
     - vessel
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
     - ./docker/nginx/h5bp:/etc/nginx/h5bp
     - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.1-fpm
    networks:
     - vessel
    volumes:
     - .:/var/www/html
     - ./docker/php/php-fpm.conf:/etc/php/7.1/fpm/php-fpm.conf
     - ./docker/php/xdebug.ini:/etc/php/7.1/mods-available/xdebug.ini
     - ./docker/phpwww.conf:/etc/php/7.1/fpm/pool.d/www.conf
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: vessel/node
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - vessel
  mysql:
    image: mysql:5.7
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
     - vesselmysql:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - vessel
  redis:
    image: redis:alpine
    volumes:
     - vesselredis:/data
    networks:
     - vessel
networks:
  vessel:
    driver: "bridge"
volumes:
  vesselmysql:
    driver: "local"
  vesselredis:
    driver: "local"
